import math, statistics
from tenx.engine import _run_decision_core
from empirical.backbone import run_empirical_reference
SEEDS=[2,7,13,23,31,43,59]
def run_campaign():
    runs=[_run_decision_core(s) for s in SEEDS]; pts=[r['decision']['x'] for r in runs]; cx=sum(p[0] for p in pts)/len(pts); cy=sum(p[1] for p in pts)/len(pts); ds=[math.dist(p,[cx,cy]) for p in pts]
    safe=[r['decision']['safety_lcb'] for r in runs]; info=[r['decision']['information'] for r in runs]; emp=run_empirical_reference(); disp=max(ds); safe_share=sum(v>=0 for v in safe)/len(safe)
    state='SHADOW_EXPERIMENT_REVIEW' if safe_share==1 and min(safe)>=0 and disp<=0.45 else 'HOLD_AND_RECALIBRATE'
    return {'campaign':'Sequential Experiment Campaign','campaign_identity':'safe-recipe dispersion + information frontier','scenario_count':len(runs),'scenario_seeds':SEEDS,'state':state,'recipe_centroid':[round(cx,5),round(cy,5)],'recipe_dispersion':round(disp,5),'mean_recipe_dispersion':round(statistics.mean(ds),5),'minimum_safety_lcb':round(min(safe),5),'safe_selection_share':safe_share,'mean_information_value':round(statistics.mean(info),5),'scenario_matrix':[{'seed':s,'x':r['decision']['x'],'safety_lcb':r['decision']['safety_lcb'],'information':r['decision']['information'],'objective_rmse':r['model_validation']['objective_rmse'],'safety_rmse':r['model_validation']['safety_rmse']} for s,r in zip(SEEDS,runs)],'ai_synthesis':{'why':f'All safe selections={safe_share:.0%}; maximum recipe dispersion={disp:.3f}.','challenge':'A high-information recipe is not qualification-worthy if posterior safety confidence or campaign stability fails.','recommended_operator_action':'Run only the next shadow experiment, update the GP, and re-evaluate qualification.','abstention_conditions':['negative safety LCB','recipe instability','calibration drift','outside design region']},'action_queue':['inspect NIST/plant evidence surface','run recommended shadow experiment','record response and update GP','recompute SAFE-TRUST','qualify or HOLD'],'human_authority':'PROCESS_DEVELOPMENT_ENGINEER','autonomous_execution':False,'empirical_provenance':{'mode':emp.get('data_mode'),'promotion':emp.get('empirical_promotion')}}
